### ISSUE TITLE
Employee Controller Error

### ISSUE THREAD

**Issue by jjhayter** [exceptionnotfound/DotNetCqrsDemo#2]
Thank you for the sample, I have been enjoying looking it over.

From what I see in the Initializer project to populate the Write Model it looks like the Create Employee Command is also assigning an Employee however later down you have explicitly configured to assign employees on the Location Controller; this makes perfect sense as each command is nearly atomic this way. Is it safe to say that the extra logic in the Employee Create method can simply be removed/commented out?

        [HttpPost]
        [Route("create")]
        public IHttpActionResult Create(CreateEmployeeRequest request)
        {
            var command = _mapper.Map<CreateEmployeeCommand>(request);
            _commandSender.Send(command);

            //var locationAggregateID = _locationRepo.GetByID(request.LocationID).AggregateID;
            //var assignCommand = new AssignEmployeeToLocationCommand(locationAggregateID, request.LocationID, request.EmployeeID);
            //_commandSender.Send(assignCommand);
            return Ok();
        }

**Comment by exceptionnotfound** [comment]
No, we cannot remove this logic, as one of our business rules is that employees must be assigned to a location.  This logic is designed to assign a *new* employee to a location; the one in the Location controller is designed to assign an *existing* employee to a location.
